config/routes.rb
Rails.application.routes.draw do

  get 'pages/template1'
  get 'pages/template2'
  get 'pages/search'
  get 'pages/category'
  get 'pages/contacts'
  get 'pages/main'
  get 'pages/alternate'
  get 'pages/about'
  get 'pages/404'
  get 'pages/services'
  get 'pages/popup'

  root 'pages#main'

  get "admin/login" => "sessions#new"
  post 'admin/login' => 'sessions#create', as: :login
  get "admin/logout" => "sessions#destroy", as: :logout

  get 'search' => "categories#search"
    get 'images' => 'images#index'

  get 'categories/show'
  get 'attachments/download/:id' => 'attachments#download', as: :download

    resources :categories, only: [:index, :show]
    resources :products, only: [:index, :show]
    resources :dealers, only: [:index, :show]

  namespace :admin do
    get "/" => "admin#index", as: :root

    post "settings/set" => "admin#set", as: :stng_set
    resources :products do
      resources :factoids
      resources :complects
      resources :attachments
      resources :properties
    end
    resources :faqs
    resources :projects
    resources :recommendations

    resources :categories
    resources :dealers

    resources :adcats
    resources :images

    get "settings" => "settings#get"
    post "settings" => "settings#set"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
	has_many :attachments, through: :products
	has_many :galleries, as: :imagable
	has_many :images, through: :galleries
	has_many :products_images, as: :gallery, through: :products, source: :images

	validates :name, :presence => true
	validates :slug, :presence => true

	serialize :meta_keywords, Array
	serialize :search_tags, Array

	extend FriendlyId
	friendly_id :name, :use => [:slugged, :history, :finders]

	def normalize_friendly_id(text)
		text.to_slug.normalize(transliterations: :russian).to_s
	end

	def self.get_metakeywords
		arr = self.select(:meta_keywords)
		.map(&:meta_keywords)
		.flatten.compact.uniq
	end


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

	before_action :require_user
	layout "admin"

	def index
		@categories = Category.order :name
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		@category.images = Image.where(id: params[:category][:images])
		if @category.save
			redirect_to edit_admin_category_path(@category)
		else
			render :template => "admin/categories/new"
		end
	end

	def edit
		@category = Category.friendly.find(params[:id])
	end


	def update
		@category = Category.friendly.find(params[:id])
		@category.images = Image.where(id: params[:category][:images])
		if @category.update(category_params)
			redirect_to edit_admin_category_path(@category)
		else
			redirect_to edit_admin_category_path(@category)
		end
	end

	def destroy
		@category = Category.friendly.find(params[:id])

		if @category.products.any?
			flash[:notice] = "Невозможно удалить категорию, пока к ней привязаны продукты"
			redirect_to edit_admin_category_path @category.id
		else
			@category.destroy
			redirect_to admin_categories_path
		end
	end

	private
	def category_params
	    params.require(:category).permit(:name, :description, :meta_title, :meta_description, :slug, :active, :visible, :images, :email,
		meta_keywords: [],
		search_tags: [])
	end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	include Setng

	caches_action :search, expires_in: 1.hour

	def search
		@cat_order = Setng::get("cat_order").split("|")
		@categories = []
		used_cat_ids = []
		used_adcat_ids = []
		used_product_ids = []

		@search_tags = Setng::get("search_tags")

		@cat_order.each do |item|
			tmp = item.split("/")
			type = tmp[0]
			id = tmp[1]

			if type == "adcat"
				@categories.push Adcat.find(id)
				used_adcat_ids.push(id)
			elsif type == "cat"
				category = Category.find(id)
				category.products = category.products.to_a.reject do |p|
					!p.visible
				end

				@categories.push category
				used_cat_ids.push(id)
			elsif type == "product"
				@categories.push Product.find(id)
				used_product_ids.push(id)
			end
		end

		Category.all.each do |cat|
			unless used_cat_ids.include? cat.id.to_s

				cat.products = cat.products.to_a.reject do |p|
					!p.visible
				end
				@categories.push cat
			end
		end

		Product.without_cat.each do |cat|
			@categories.push cat unless used_product_ids.include? cat.id.to_s
		end

		Adcat.all.each do |cat|
			@categories.push cat unless used_adcat_ids.include? cat.id.to_s
		end

	end

	def show

		@category = Category.friendly.find(params[:id])


		if !@category.active && !current_user
			render "errors/access"
		end

		if request.path != category_path(@category)
			return redirect_to @category, :status => :moved_permanently
		end

		@attachments = {}
		Rails.logger.debug(@cateogory)
		@category.attachments.each do |a|
			@attachments[a.group] ||= []
			@attachments[a.group].push a
		end


		prepare_meta_tags	title: @category.meta_title.presence || @category.name,
							description: @category.meta_description.presence || @category.description,
							keywords: @category.meta_keywords.reject {|k| k == ''} || []


	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/search.html.slim
- title "Поиск пластгрупп"

.p-search
    form.p-search__form action=""
        .search-field.search-field--empty
            .search-field__field
                .search-field__top
                    span#search-hidden.search-field__backhidden
                    input#search-field placeholder="Продукты" type="text" value="Продукты" /
            hr.search-field__divider/
            .search-field__example
                p.search-field__esamples
                    | Например:
                    - @search_tags.each do |t|
                        a.tag href="#" = t
                p.search-field__esamples--hidden
                    a.dashed href="#"  Показать все продукты


    .p-search__grid.grid
        #search-results.grid__row.grid__row--stretch

            .search-notification
                form.contacts-form action=""
                h2.contacts-form__title
                    | Мы не нашли похожие продукты на сайте
                .contacts-form__feedback
                    p Напишите нам. Мы ответим на все вопросы, проконсультируем и предложим решение.
                .contacts-form__inputs
                    .input-suggest
                        input.contacts-form__input placeholder="Тема" type="text" /
                        .input-suggest__dropdown
                          .input-suggest__option
                            | Пример темы 1
                          .input-suggest__option
                            | Пример темы 2
                          .input-suggest__option
                            | Пример темы 3
                    input.contacts-form__input placeholder=("Вопрос или описание проекта") type="text" /
                    input.contacts-form__input placeholder=("Эл. почта или телефон") type="text" /
                input.contacts-form__btn type="submit" value=("Оставить заявку") /
                a.contacts-form__file href="#"  Добавить смету или план проекта
                input#file-input hidden="true" type="file" /

            - @categories.each do |c|
                - if c.class.to_s.downcase == "category"

                    - if c.visible

                        .mix.grid-1-4.p-search__item data-filter=c.search_tags.push(c.name).compact.uniq.flatten.join(" ")
                          .search-card
                            h3.search-card__name
                                - if c.active
                                    = link_to c.name, category_path(c)

                                - else
                                    = c.name

                            - if c.products.empty?
                                p.search-card__description
                                    == preview c.description if c.description

                            - else

                                ul.search-card__list
                                    - c.products.each do |p|
                                        li.search-card__item data-subfilter=p.search_tags.push(p.name).compact.uniq.flatten.join(" ")
                                            - if p.active
                                                = link_to p.listname.presence || p.name, product_path(p)
                                            - else
                                                = p.listname.presence || p.name


                - elsif c.class.to_s.downcase == "product"

                    .mix.grid-1-4.p-search__item data-filter=c.search_tags.push(c.name).compact.uniq.flatten.join(" ")
                      .search-card
                        h3.search-card__name
                            - if c.active
                                = link_to c.listname.presence || c.name, product_path(c)
                            - else
                                span = c.listname.presence || c.name
                        p.search-card__description
                            == preview c.description if c.description

                - else

                    .mix.mix-all.grid-1-4.p-search__item data-filter=""
                        == c.html

            - if @categories.length % 4 > 0
                - ((@categories.length % 4 - 4) * -1).times
                    .mix.grid-1-4.p-search__item.js-empty

= render partial: "gBenefitsBlue"

= content_for :footer_class
    | footer--blue

= content_for :scripts

    script src="/js/jquery.mixitup.min.js"
    script src="/js/search.js"

app/views/categories/show.html.slim
= content_for :styles
	= stylesheet_link_tag    "/css/category.css", media: "all"

= content_for :container_class
    | container--blue container--category

.page
    h1.page__title
        = @category.name

- if @category.products.any?
    .category-products
        .category-products__inner
            .category-products__links
                - @category.products.each do |p|
                    - if p.visible
                        .category-products__link

                            - if p.active

                                = link_to product_path(p), :data => {:point => 1} do ||
                                    = p.listname.presence || p.name
                                    span.dot

                            - else
                                = p.listname.presence || p.name
                                span.dot

            - if @category.image?
                .category-products__image
                    img src="/img/image.png" width="900" alt="" /


.content
    .content__inner
      .col.col.col--left
        h2 = @category.name
        .content__factoid
          aside.factoid.factoid--top.u-empty-field
            .feature
              .feature__caption Диаметры корпуса,&nbsp;мм
              .feature__value 600–3700
            p Отдельно производим <nobr>гипер-резервуары</nobr> диаметром более 5&nbsp;метров
            p
              a.factoid__link href="#" О корпусе из стеклопластика

        == @category.description

        .links-list
          .links-list__row
            - @attachments.each do |i, a|

                .links-list__column
                  h3.links-list__title = i
                  ul.links-list__list
                    - a.each do |at|
                        li.links-list__item
                            - case at.type
                                - when "popup"
                                    = link_to at.name, "#", {:class => "popup-attachment"}
                                - when "blank"
                                    = link_to download_path(at), {:target => "_blank"} do ||
                                        = at.name
                                - else
                                    = link_to download_path(at) do ||
                                        = at.name

                                        // span.links-list__annotation Архив · 2,3 МБ<span>↓</span>

          .shadow
            span.shadow__top
            .links-list__item
              a.shadow__text href="#"
                span Показать все документы

.gallery.section
    .gallery__inner
        h2.gallery__title Фотографии продуктов, производства и установки
        - images = @category.images + @category.products_images
        - images.uniq!

        - images.sort_by! { |i| i.text_preview ? 0 : 1}

        - rows_len = 2

        - for i in 0..rows_len
            - if images.any?
                .gallery__row
                    - if images.first.text_preview && first = images.shift
                        - if i == 0

                            .gallery__item.gallery__item--narrow
                                p.gallery__text = first.text
                            a.gallery__item.gallery__item--wide href="#"
                                .gallery__image style="background-image: url(#{first.file})"

                        - else

                            a.gallery__item.gallery__item--wide href="#"
                                .gallery__image style="background-image: url(#{first.file})"
                            .gallery__item.gallery__item--narrow
                                p.gallery__text = first.text
                    - else

                        - if i == rows_len
                            - for e in 0..2
                                - if image = images.shift
                                    a.gallery__item.gallery__item--narrow href="#"
                                        .gallery__image style="background-image: url(#{image.file})"
                                        - if e == 2 && images.any?
                                            .gallery__hover
                                              p Все #{@category.products_images.length} фотографий


                        - else
                            - for e in 0..1
                                - if image = images.shift
                                    a.gallery__item class="gallery__item--#{e == i ? 'wide' : 'narrow'}" href="#" data-gallery-popup="" data-gallery-caption=image.text data-gallery-group="1" data-gallery-group-name="продуктов"
                                        /.gallery__image style="background-image: url(#{image.file})"
										= image_tag image.file

= render partial: "g_benefits"

= render partial: "application_form"

= render partial: "gallery_overlay"

= content_for :scripts
    script src="/js/raphael.min.js"
    script src="/js/category.js"