config/routes.rb
Rails.application.routes.draw do

  get 'pages/template1'
  get 'pages/template2'
  get 'pages/search'
  get 'pages/category'
  get 'pages/contacts'
  get 'pages/main'
  get 'pages/alternate'
  get 'pages/about'
  get 'pages/404'
  get 'pages/services'
  get 'pages/popup'

  root 'pages#main'

  get "admin/login" => "sessions#new"
  post 'admin/login' => 'sessions#create', as: :login
  get "admin/logout" => "sessions#destroy", as: :logout

  get 'search' => "categories#search"
    get 'images' => 'images#index'

  get 'categories/show'
  get 'attachments/download/:id' => 'attachments#download', as: :download

    resources :categories, only: [:index, :show]
    resources :products, only: [:index, :show]
    resources :dealers, only: [:index, :show]

  namespace :admin do
    get "/" => "admin#index", as: :root

    post "settings/set" => "admin#set", as: :stng_set
    resources :products do
      resources :factoids
      resources :complects
      resources :attachments
      resources :properties
    end
    resources :faqs
    resources :projects
    resources :recommendations

    resources :categories
    resources :dealers

    resources :adcats
    resources :images

    get "settings" => "settings#get"
    post "settings" => "settings#set"
  end
end

app/models/adcat.rb
class Adcat < ActiveRecord::Base

	validates :name, :presence => true
	validates :html, :presence => true
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :product
	self.inheritance_column = nil


	mount_uploader :file, AttachmentUploader

	validates :name, :presence => true
	validates :file, :presence => true
	validates :type, :presence => true

	def types_list
		{ "Всплывающее окно"=> :popup ,  "Скачать" => :download , "В новом окне" => :blank }
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
	has_many :attachments, through: :products
	has_many :galleries, as: :imagable
	has_many :images, through: :galleries
	has_many :products_images, as: :gallery, through: :products, source: :images

	validates :name, :presence => true
	validates :slug, :presence => true

	serialize :meta_keywords, Array
	serialize :search_tags, Array

	extend FriendlyId
	friendly_id :name, :use => [:slugged, :history, :finders]

	def normalize_friendly_id(text)
		text.to_slug.normalize(transliterations: :russian).to_s
	end

	def self.get_metakeywords
		arr = self.select(:meta_keywords)
		.map(&:meta_keywords)
		.flatten.compact.uniq
	end


end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :factoids
end

app/models/complect.rb
class Complect < ActiveRecord::Base
	belongs_to :product
	self.inheritance_column = nil

	serialize :coords, JSON

	def types_list
		["Базовая", "Дополнительная"]
	end
end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
end

app/models/factoid.rb
class Factoid < ActiveRecord::Base
	belongs_to :product
	belongs_to :client
	self.inheritance_column = nil

    mount_uploader :file, ImageUploader

	def types_list
		["ГОСТ", "Обычный", "Параметры", "Клиент", "Пустой"]
	end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
    belongs_to :imagable, polymorphic: true
    belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base

    has_many :galleries, dependent: :destroy
    has_many :product, :through => :galleries, :source => :imagable, :source_type => "Product"
    has_many :categories, :through => :galleries, :source => :imagable, :source_type => "Category"

    mount_uploader :file, ImageUploader

    validates :file, :presence => true

	scope :shared, -> {where(:display => true)}

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_and_belongs_to_many :categories
	has_many :factoids
	has_many :complects
	has_many :attachments
	has_many :properties
	has_many :galleries, as: :imagable
	has_many :images, through: :galleries
	mount_uploader :complect_image, ImageUploader

	accepts_nested_attributes_for :factoids, :allow_destroy => true
	accepts_nested_attributes_for :complects, :allow_destroy => true
	accepts_nested_attributes_for :attachments, :allow_destroy => true
	accepts_nested_attributes_for :properties, :allow_destroy => true

	validates :name, :presence => true
	validates :slug, :presence => true

	serialize :properties_options, Array
	serialize :meta_keywords, Array
	serialize :search_tags, Array


	extend FriendlyId
	friendly_id :name, :use => [:slugged, :history, :finders]

	def normalize_friendly_id(text)
		text.to_slug.normalize(transliterations: :russian).to_s
	end


	def self.get_fields_avalible
		arr = self.select(:properties_options)
		.map(&:properties_options)
		.flatten.compact
		.map do |obj|
			obj["fields"]
		end
		.flatten.compact.uniq
	end

	def self.get_metakeywords
		arr = self.select(:meta_keywords)
		.map(&:meta_keywords)
		.flatten.compact.uniq
	end

	scope :without_cat, -> {joins(:categories).where(:categories => {:id => nil})}

	scope :used, -> {where(:using => true)}

end

app/models/project.rb
class Project < ActiveRecord::Base
    mount_uploader :logo, ImageUploader
end

app/models/property.rb
class Property < ActiveRecord::Base
    belongs_to :product

    mount_uploader :image, ImageUploader
    mount_uploader :dwg, AttachmentUploader
    mount_uploader :pdf, AttachmentUploader
    serialize :values, Array
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
    mount_uploader :file, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/admin/index.html.slim
javascript:
	window.admin_stng_set_path = "#{admin_stng_set_path}"
	window.main_menu = '#{{@main_menu.to_json}}'
	window.top_menu = '#{{Setng::get('top_menu').to_json}}'
	window.bottom_menu = '#{{Setng::get('bottom_menu').to_json}}'

.row
	.col-md-12.m-b
		h1 Панель управления #{@site_name}

.row

	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Продукт на главной
			.panel-body

				= select "main", "product", options_for_select(Product.all.map {|t| [t.name, t.id]}, @main_product), {}, { :class => "form-control"}

				coffee:
					$("#main_product").on "change", (e) ->
						$.post admin_stng_set_path,
							parameter: "main_product"
							value: $(e.currentTarget).val()

	.col-md-8.col-lg-6
		.panel.panel-default
			.panel-heading Примеры поисковых запросов
			.panel-body

				= select "search", "tags", options_for_select(@search_tags.map {|t| [t, t]}, @search_tags), {}, { :multiple => true}
				javascript:
					$("#search_tags").selectize({
						onChange: function(values){
							console.log(values)
							$.post("#{admin_stng_set_path}", {parameter: "search_tags", value: values})
						},
						delimiter: ',',
						persist: false,
						create: function(input) {
							return {
								value: input,
								text: input
							}
						}
					})

	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Реквизиты
			.panel-body
				.form-group
					= text_field_tag "creds", Setng::get("creds_link"), {:class => "form-control"}

				= button_tag "Сохранить", {:class => "btn btn-default creds-btn", :data => {:disable_with => "Подождите..."}}

			coffee:
				$ ".creds-btn"
				.on "click", (e) ->
					$btn = $ e.currentTarget
					$btn.prop "disabled", true
					text = $btn.text()
					$btn.text $btn.data "disable-with"


					$.post "#{admin_stng_set_path}", {
						parameter: "creds_link"
						value: $("#creds").val()
						}, ->
							$btn.prop "disabled", false
							$btn.text text



	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Email для заявок по умолчанию
			.panel-body
				.form-group
					= text_field_tag "default_email", Setng::get("default_email"), {:class => "form-control"}

				= button_tag "Сохранить", {:class => "btn btn-default d-email-btn", :data => {:disable_with => "Подождите..."}}

			coffee:
				$ ".d-email-btn"
				.on "click", (e) ->
					$btn = $ e.currentTarget
					$btn.prop "disabled", true
					text = $btn.text()
					$btn.text $btn.data "disable-with"


					$.post "#{admin_stng_set_path}", {
						parameter: "default_email"
						value: $("#default_email").val()
						}, ->
							$btn.prop "disabled", false
							$btn.text text


	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Количество изделий
			.panel-body
				.form-group
					= text_field_tag "products_quantity", Setng::get("products_quantity"), {:class => "form-control"}

				= button_tag "Сохранить", {:class => "btn btn-default pq-btn", :data => {:disable_with => "Подождите..."}}

			coffee:
				$ ".pq-btn"
				.on "click", (e) ->
					$btn = $ e.currentTarget
					$btn.prop "disabled", true
					text = $btn.text()
					$btn.text $btn.data "disable-with"


					$.post "#{admin_stng_set_path}", {
						parameter: "products_quantity"
						value: $("#products_quantity").val()
						}, ->
							$btn.prop "disabled", false
							$btn.text text



	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Адрес блога
			.panel-body
				.form-group
					= text_field_tag "blog", Setng::get("blog_link"), {:class => "form-control"}

				= button_tag "Сохранить", {:class => "btn btn-default blog-btn", :data => {:disable_with => "Подождите..."}}

			coffee:
				$ ".blog-btn"
				.on "click", (e) ->
					$btn = $ e.currentTarget
					$btn.prop "disabled", true
					text = $btn.text()
					$btn.text $btn.data "disable-with"


					$.post "#{admin_stng_set_path}", {
						parameter: "blog_link"
						value: $("#blog").val()
						}, ->
							$btn.prop "disabled", false
							$btn.text text



	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Главное меню
			= form_tag({action: "set", controller: "admin"}, class: "main-menu-form") do
				= hidden_field_tag :parameter, "main_menu"

				ul#menu_list.list-group.sortable

					- [pages_about_path, search_path, Setng::get("blog_link")].each do |m|

						li.list-group-item data-id="#{m}"
							.drag-handle
								i.fa.fa-bars.fa-lg

							= hidden_field_tag "value[][name]", m
							- item = (@main_menu.detect() {|a| a['name'] == m} || {})

							.input-group
								span.input-group-addon
									= check_box_tag "value[][enabled]", nil, item['enabled'], { :class => ""}
								= text_field_tag "value[][text]", item['text'] , {:class => "form-control", :placeholder => m}

			coffee:
				$(document).on "ready", ->
					$f = $ ".main-menu-form"
					timer = null
					submit = ->

						clearTimeout timer if timer
						timer = setTimeout( ->
							$f.ajaxSubmit()
						, 1000)


					Sortable.create $("#menu_list")[0],
						handle: ".drag-handle"
						group: "menu_list"
						store:
							get: (sortable) ->
								data = JSON.parse main_menu
								res = data.map (item) ->
									item.name
								return res

							set: submit

					$f.on "change", "input", submit


	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Верхнее меню продуктов
			= form_tag({action: "set", controller: "admin"}, class: "top-menu-form") do
				= hidden_field_tag :parameter, "top_menu"

				ul#top_menu.list-group.sortable

					- Product.used.each do |p|

						li.list-group-item data-id=p.id
							.drag-handle
								i.fa.fa-bars.fa-lg

							label.control-label.checkbox
								= check_box_tag 'value[]', p.id, Setng::get('top_menu').include?(p.id.to_s), { :class => "using-checkbox"}
								= p.name

			coffee:
				$(document).on "ready", ->
					$f = $ ".top-menu-form"
					timer = null
					submit = ->

						clearTimeout timer if timer
						timer = setTimeout( ->
							$f.ajaxSubmit
								beforeSubmit: (arr, $form, opts) ->

									arr = arr.map (i) ->
										console.log i
										return i.id
						, 1000)


					Sortable.create $("#top_menu")[0],
						handle: ".drag-handle"
						group: "top_list"
						store:
							get: (sortable) ->
								data = JSON.parse top_menu
								_.each $('#top_menu input'), (el) ->
									data.push el.value if data.indexOf(el.value) is -1
								return data

							set: submit

					$f.on "change", "input", submit



	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Нижнее меню продуктов
			= form_tag({action: "set", controller: "admin"}, class: "bottom-menu-form") do
				= hidden_field_tag :parameter, "bottom_menu"

				ul#bottom_menu.list-group.sortable

					- Product.used.each do |p|

						li.list-group-item data-id=p.id
							.drag-handle
								i.fa.fa-bars.fa-lg

							label.control-label.checkbox
								= check_box_tag 'value[]', p.id, Setng::get('bottom_menu').include?(p.id.to_s), { :class => "using-checkbox"}
								= p.name

			coffee:
				$(document).on "ready", ->
					$f = $ ".bottom-menu-form"
					timer = null
					submit = ->

						clearTimeout timer if timer
						timer = setTimeout( ->
							$f.ajaxSubmit()
						, 1000)


					Sortable.create $("#bottom_menu")[0],
						handle: ".drag-handle"
						group: "bottom_list"
						store:
							get: (sortable) ->
								data = JSON.parse bottom_menu
								_.each $('#bottom_menu input'), (el) ->
									data.push el.value if data.indexOf(el.value) is -1
								return data

							set: submit

					$f.on "change", "input", submit



	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Порядок категорий

			ul#cat-order.list-group.sortable
				- Category.all.each do |c|
					li.list-group-item data-id="cat/#{c.id}"
						= c.name

				- Adcat.all.each do |c|
					li.list-group-item data-id="adcat/#{c.id}"
						= c.name

				- Product.without_cat.each do |c|
					li.list-group-item data-id="product/#{c.id}"
						= c.name


			javascript:
				Sortable.create($("#cat-order")[0], {
					store: {
						get: function(sotrable){
							var result = "#{@cat_order ? @cat_order : ''}"
							return result ? result.split("|") : [];
						},

						set: function(sortable){
							var result = sortable.toArray().join("|")
							$.post("#{admin_stng_set_path}", {parameter: "cat_order", value: result})
						}
					}
				})


	.col-md-4.col-lg-3
		.panel.panel-default
			.panel-heading Продукты на главной



			ul#main-list.list-group.sortable
				- Category.all.each do |c|
					li.list-group-item data-id="cat/#{c.id}"
						.drag-handle
							i.fa.fa-bars.fa-lg
						label.control-label.checkbox
							= check_box_tag "cat/#{c.id}_using", "", @main_list_using.include?("cat/#{c.id}"), { :class => "using-checkbox"}
							= c.name
						= select_tag "cat/#{c.id}_example", options_from_collection_for_select(c.products, "id", "name", JSON.parse(@main_list_examples)["cat/#{c.id}"]), { :class => "form-control example-input", :include_blank => true}

				- Product.all.each do |c|
					li.list-group-item data-id="product/#{c.id}"
						.drag-handle
							i.fa.fa-bars.fa-lg
						label.control-label.checkbox
							= check_box_tag "product/#{c.id}_using", "", @main_list_using.include?("product/#{c.id}"), { :class => "using-checkbox"}
							= c.name

			javascript:
				window.onload = function(){

					var main_list_using = []
					try {
						main_list_using = JSON.parse('#{{@main_list_using}}')
					} catch (e){
						console.log(e);
					}

					var main_list_examples = {}
					try {
						main_list_examples = JSON.parse('#{{@main_list_examples}}')
					} catch (e){
						console.log(e);
					}

					$("body").on("change", ".example-input", function(e){

						var $el = $(e.currentTarget)
						,	id = $el.parents("li").data("id")
						,	value = $el.val()

						main_list_examples[id] = value
						$.post("#{admin_stng_set_path}", {parameter: "main_list_examples", value: JSON.stringify(main_list_examples)})

					})


					$("body").on("change", ".using-checkbox", function(e){
						var $el = $(e.currentTarget)
						,	id = $el.parents("li").data("id")
						,	action = e.currentTarget.checked

						if(action){
							main_list_using.push(id)
						} else {
							var i = main_list_using.indexOf(id)
							if(i > -1){
								main_list_using.splice(i, 1)
							}
						}
						$.post("#{admin_stng_set_path}", {parameter: "main_list_using", value: JSON.stringify(main_list_using)})
					})

					Sortable.create($("#main-list")[0], {
						handle: ".drag-handle",
						store: {
							get: function(sortable){
								var result = "#{@main_list_order ? @main_list_order : ''}"
								console.log(sortable)
								return result ? result.split("|") : [];
							},

							set: function(sortable){
								var result = sortable.toArray().join("|")
								$.post("#{admin_stng_set_path}", {parameter: "main_list_order", value: result})
							}
						}
					})

				}



= content_for :script

	script src='http://malsup.github.io/jquery.form.js'